/* 
* Autogenerated service code 
* Variables (text between %) must have been replaced when code is autogenerated
*/

package services;

import java.util.ArrayList;
import java.util.Collection;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.Assert;

import repositories.GarageRepository;
import domain.Garage;
import domain.Motorbike;

@Service
@Transactional
public class GarageService {

	// Managed repository -----------------------------------------------------
	@Autowired
	private GarageRepository garageRepository;

	// Ancillary services -----------------------------------------------------

	// Constructor ------------------------------------------------------------
	public GarageService(){
		super();
	}

	// Simple CRUD methods ----------------------------------------------------
	public Garage create(){
		Garage newbye;
		Collection<Motorbike> motos = new ArrayList<Motorbike>();
		
		newbye = new Garage();
		
		newbye.setMotorbikes(motos);
		
		return newbye;
	}

	public void save( Garage entity ){
		Assert.notNull(entity);
		
		this.garageRepository.save( entity );
	}

//HAY QUE ARREGLAR METODO ELIMINAR SI TIENE RELACION CON ALGUNA MOTO
	public void delete( Garage entity ){
		Assert.isTrue( entity.getId()!=0 );
		Assert.isTrue( this.garageRepository.exists(entity.getId() ));
		
		this.garageRepository.delete( entity );
	
		Assert.isTrue( !this.garageRepository.exists(entity.getId() ));
	}

	public Garage findOne( int id ){
		Assert.isTrue( id != 0);
		
		Garage res;
		
		res = this.garageRepository.findOne( id );
		
		return res;
	}

	public Collection<Garage> findAll(){
		Collection<Garage> res;
		
		res = garageRepository.findAll();
		
		return res;
	}

	// Other business methods -------------------------------------------------

	// Ancillary methods ------------------------------------------------------

}
