/* 
* Autogenerated service code 
* Variables (text between %) must have been replaced when code is autogenerated
*/

package services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.Assert;

import repositories.WorkShopServiceRepository;
import domain.WorkShopService;

@Service
@Transactional
public class WorkShopServiceService {

	// Managed repository -----------------------------------------------------
	@Autowired
	private WorkShopServiceRepository workshopserviceRepository;

	// Ancillary services -----------------------------------------------------

	// Constructor ------------------------------------------------------------
	public WorkShopServiceService(){
		super();
	}

	// Simple CRUD methods ----------------------------------------------------
//	public WorkShopService create(){
//		WorkShopService newbye;
//		
//		newbye = new WorkShopService();
//		
//		return newbye;
//	}

//	public void save( WorkShopService entity ){
//		checkModificationPreconditions( entity );
//		
//		this.workshopserviceRepository.save( entity );
//	}

//	public void delete( WorkShopService entity ){
//		Assert.isTrue( entity.getId()!=0 );
//		Assert.isTrue( this.workshopserviceRepository.exists(entity.getId() ));
//		
//		this.workshopserviceRepository.delete( entity );
//		
//		Assert.isTrue( !this.workshopserviceRepository.exists(entity.getId() ));
//	}

//	public WorkShopService findOne( int id ){
//		Assert.isTrue( id != 0);
//		
//		WorkShopService res;
//		
//		res = this.workshopserviceRepository.findOne( id );
//		
//		return res;
//	}

//	public Collection<WorkShopService> findAll(){
//		Collection<WorkShopService> res;
//		
//		res = workshopserviceRepository.findAll();
//		
//		return res;
//	}

	// Other business methods -------------------------------------------------

	// Ancillary methods ------------------------------------------------------

}
