/* 
* Autogenerated converter code 
* Variables (text between %) must have been replaced when code is autogenerated
*/
package converters;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import repositories.DiscussionMessageRepository;
import domain.DiscussionMessage;

@Component
@Transactional
public class StringToDiscussionMessageConverter implements Converter<String, DiscussionMessage> {

	@Autowired
	DiscussionMessageRepository discussionmessageRepository;

	@Override
	public DiscussionMessage convert(String text) {
		DiscussionMessage result;
		int id;

		try {
			id = Integer.valueOf(text);
			result = discussionmessageRepository.findOne(id);
		} catch (Throwable oops) {
			throw new IllegalArgumentException(oops);
		}

		return result;
	}

}
