/* 
* Autogenerated converter code 
* Variables (text between %) must have been replaced when code is autogenerated
*/
package converters;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import repositories.MotorbikeRepository;
import domain.Motorbike;

@Component
@Transactional
public class StringToMotorbikeConverter implements Converter<String, Motorbike> {

	@Autowired
	MotorbikeRepository motorbikeRepository;

	@Override
	public Motorbike convert(String text) {
		Motorbike result;
		int id;

		try {
			id = Integer.valueOf(text);
			result = motorbikeRepository.findOne(id);
		} catch (Throwable oops) {
			throw new IllegalArgumentException(oops);
		}

		return result;
	}

}
