/* 
* Autogenerated interface code 
* Variables (text between %) must have been replaced when code is autogenerated
*/
package repositories;

import java.util.Collection;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import domain.Motorbike;

@Repository
public interface MotorbikeRepository extends JpaRepository<Motorbike, Integer>{
	
	@Query("select m from Motorbike m ORDER BY m.drivingTime DESC")
	Collection<Motorbike> findAllMotorbikesOrderedByDrivingTime();
	
	@Query("select m from Motorbike m where m not in (select d.motorbike from DeliveryMan d where d.motorbike is not null)")
	Collection<Motorbike> findFreeMotorbikes();
			
	@Query("select count(m) from Motorbike m where m.garage.id = ?1")
	Integer findTotalMotorbikesByGarage(int garageId);
}
